services:
  app:
    image: todo-frontend-prod
    build:
      context: ./todo-frontend # The context will pick this directory as the "build context"
      dockerfile: Dockerfile # This will simply tell which dockerfile to read
    environment:
      - VITE_BACKEND_URL=http://localhost:8080/api
    container_name: todo-frontend-prod # This will name the container hello-front-dev


  debug-helper:
    image: busybox
    container_name: debug-helper
    command: ["sh", "-c", "while true; do sleep 3600; done"]

  mongo:
    image: mongo
    ports:
     - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database

    volumes: 
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./todo-backend/mongo_data:/data/db #for data persistence
  
  redis:
    image: redis
    ports:
     - 6378:6379
    command: ['redis-server', '--appendonly', 'yes']
    volumes: # Declare the volume
      - ./todo-backend/redis_data:/data

  server:
    build:
      context: ./todo-backend           
      dockerfile: Dockerfile
    image: todo-backend-prod
    volumes:
      - ./todo-backend:/usr/app/src
    environment: 
      - REDIS_URL=redis://redis:6379
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database
    depends_on:
      - mongo
      - redis

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy-prod
    depends_on:
      - app
      - server
      - mongo
      - redis